name: GitHub API Interaction

on:
  push:
    branches:
      - main  # Adjust if your default branch has a different name

jobs:
  call_github_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Repository Details
        env:
          API_TOKEN: ${{ secrets.api_token2 }}
        run: |
          curl -H "Authorization: Bearer $API_TOKEN" \
               -H "accept: application/json" \
               "https://api.github.com/repos/brytoncooper/commandBackendv6"
